# SPDX-License-Identifier: MIT

require conf/machine/include/tune-xtensa-esp32s3-fdpic.inc

MACHINEOVERRIDES =. "esp32s3:esp32s3-devkitc-1-n16r8:"

MACHINE_FEATURES = ""
MACHINE_ESSENTIAL_EXTRA_RDEPENDS = "kernel-image-xipimage"

KERNEL_IMAGETYPE = "xipImage"
KERNEL_IMAGE_LINK_NAME = ""
KERNEL_IMAGETYPE_SYMLINK = "1"

IMAGE_FSTYPES = "cramfs"
IMAGE_FEATURES = ""
EXTRA_IMAGE_FEATURES = ""

SERIAL_CONSOLES = "115200;ttyS0"

ESP32S3_FLASH_SIZE = "16MB"
ESP32S3_PSRAM_SIZE = "8MB"
ESP32S3_ESP_HOSTED_SDKCONFIG = "sdkconfig.defaults.esp32s3.16n16r"
ESP32S3_PARTITION_TABLE = "partition_table.esp32s3.16m"
ESP32S3_PARTITION_TABLE_FILE = "partition-table-n16r8.csv"

TCMODE = "external-xtensa-esp32s3-fdpic"
PREFERRED_PROVIDER_virtual/kernel = "linux-xtensa"
