#!/bin/sh

for i in $(ls -r /etc/init.d/S??* 2>/dev/null); do
    [ ! -f "$i" ] && continue
    case "$i" in
        *.sh) (trap - INT QUIT TSTP; set stop; . "$i") ;;
        *) "$i" stop ;;
    esac
done
