#!/bin/sh

mkdir -p /data
grep -qs ' /data ' /proc/mounts || mount /data

for i in /etc/init.d/S??*; do
    [ ! -f "$i" ] && continue
    case "$i" in
        *.sh) (trap - INT QUIT TSTP; set start; . "$i") ;;
        *) "$i" start ;;
    esac
done
